### ISSUE TITLE
Add Switch Actuator 2/1

### ISSUE THREAD

**Issue by jafrka** [henry-spanka/homebridge-freeathome#14]
Please add following entry to the switch part in the index.js
`case '100E':`
 `          return ['BuschJaegerSchaltAktorAccessory', false];`

Thank you.

**Comment by henry-spanka** [comment]
Hi,
does the accessory behave just like any other switch actuator or did you need to do any other modifications? Which model is this? Please tell me the full name as appearing in the homebridge logs (or accessory information in HomeKit)

**Comment by jafrka** [comment]
Hi,
it doesn't seem that there are further changes needed. It is a normal switch actuator (Sensor/Schaltaktor 2/1-fach für Busch-free@home®). The light can be switched via Homebridge after I made the change manually.

`[2019-10-4 22:21:06] [BuschJaegerSysAp] initialising actuator Sensor/ Schaltaktor 2/1-fach Channel 0006 with uuid ABB700C9Bxxxch0006`
`[2019-10-4 22:21:06] [BuschJaegerSysAp] initialising actuator Sensor/ Schaltaktor 2/1-fach Channel 0006 with uuid ABB700C91xxxch0006`
`[2019-10-4 22:21:06] [BuschJaegerSysAp] Initializing platform accessory 'Sensor/ Schaltaktor 2/1-fach Channel 0006'...`
`[2019-10-4 22:21:06] [BuschJaegerSysAp] Initializing platform accessory 'Sensor/ Schaltaktor 2/1-fach Channel 0006'...`

**Comment by henry-spanka** [comment]
Thanks, I have added support for the actuator in commit 9891b6cfdc5ddb70aa063f8fb7c65c3f575dc082

I will probably release a new version this or next weekend after I have reworked the device discovery (no need for white-/blacklisting anymore) which should make things a lot easier.
