### ISSUE TITLE
Connection issue after restarting homebridge (SysAP did not respond in time)

### ISSUE THREAD

**Issue by jooste** [henry-spanka/homebridge-freeathome#20]
Hi!

Still very happy with the free@home plugin, but am now running into the following issue: rebooting the computer that homebridge is running on seems to irreversibly break the free@home connection. Homebridge and the busch jaeger plugin seem to come back online again without issues, but now whenever I try to give a command to one of my F@H devices using homekit I get something like the following in my homebridge log: 

    [3/9/2020, 6:49:26 PM] [BuschJaegerSysAp] raw/ABB700CXXXXX/ch0003/idp0000/1                                                                    
    [3/9/2020, 6:49:31 PM] [BuschJaegerSysAp] SysAp did not respond in time: 0003/odp0000/1

As a result, I can turn lights on, but not off, and the status of all devices is no longer properly communicated to homekit. Reinstalling all of the docker containers fixes this, but the problem reappears as soon as I have to reboot the NAS my homebridge is running on. Have you seen anything like this before?

**Comment by jooste** [comment]
Hmm, I was just going through your closed issues, and found your suggestion in issue #10, to log on in F@H using the same user id as the API, and click around a bit. This indeed seems to remedy things, but I do wonder why? What happens that makes things go wrong, and why does manually logging in with F@H fix things?

**Comment by henry-spanka** [comment]
Hi Jost,

I don't know why F@H is doing this. I only encountered the issue when the System Access Point is rebooted. Rebooting homebridge or freeathome-api should be fine.

I haven't really invested much time into this as I think it's only a minor issue and I can live with it. No need to reboot the AP anyway.

**Comment by jooste** [comment]
Indeed, you're right! I also had to power off the sysap to do some rewiring. That must've caused it then. Well, if that's it then indeed it's overcome-able. The sysap is really only off when there's a power outage.

If I look at your installation instructions, you have something about this issue as well, but it's crossed out. It may be useful to other users to update this text? Something like:

The homebridge connection to the SysAP may suffer from connection issues when the Busch Jaeger SysAP is restarted (e.g., due to a power outage). Buttons in the homekit UI may become unresponsive, actuator states are no longer updated, and the homebridge log shows messages like:

    [BuschJaegerSysAp] SysAp did not respond in time: ...

The solution to this problem is to log into the freeathome web interface with the same user that you use for the homebridge connection, and click around a bit.

Cheers,
Joost

**Comment by henry-spanka** [comment]
I have added the documentation back to Tips & Tricks. Additionally the homebridge log now shows the following warning:

```
SysAp did not respond in time.
If this issue persists please try to login as the API user in the free@home UI. This must sometimes be done after a reboot to enable websocket notifications.
See: https://github.com/henry-spanka/homebridge-buschjaeger#tips--tricks
```

**Comment by jooste** [comment]
That's indeed also a useful addition!

Coming back to our previous discussion: It seems here that it does actually also happen when only homebridge+freeathome-api restarts/reboots. I was doing some more 'home improvement' yesterday, where I had to power down my NAS, but the SysAP stayed online. Before this reboot everything was working fine, but this morning I'm getting unresponsive lights in the home app and the same error message in the homebridge log.

This may not change anything in what can be done about this, but I thought it might be useful to know :)

**Comment by henry-spanka** [comment]
> It seems here that it does actually also happen when only homebridge+freeathome-api restarts/reboots.
I haven't noticed that yet. Maybe it happens only once the API user is logged out for X minutes. Should now be pretty clear in the docs/log message.

**Comment by jooste** [comment]
Which log message do you mean? The one in homebridge? Or does the sysap also keep a log?

**Comment by henry-spanka** [comment]
I mean the homebridge log. If web socket updates do not work then the log message should make it clear what to do to fix it.

```
SysAp did not respond in time.
If this issue persists please try to login as the API user in the free@home UI. The SysAp might disable websocket notifications if the connection is idle for too long.
See: https://github.com/henry-spanka/homebridge-buschjaeger#tips--tricks
```
