### ISSUE TITLE
Thermostat issues Since 2.0.2

### ISSUE THREAD

**Issue by Phasaeron** [henry-spanka/homebridge-freeathome#26]
Hi Henry,
I am using homebridge-freeathome with hoobs. Since the Update 2.0.2 the Roomtemparature is not showed anymore via HomeKit see image. There is always shown „auf 7° heizen“ (which is probably the lowest temparature when turned off). Also the shutters when opened completely won’t stop showing „wird geöffnet“ although they are fully rolled up.
![IMG_0003](https://user-images.githubusercontent.com/69851835/90511634-0c223d00-e15d-11ea-8b59-097b60c60f70.jpeg)

![IMG_0002](https://user-images.githubusercontent.com/69851835/90511368-a0d86b00-e15c-11ea-8504-a22c9910fbf1.jpeg)
Restarting Homebridge did not change the issue and downgrading to 2.0.1 is not possible. Just wanted to let you know. Maybe there is a error in my installation idk...hopefully I will here from you soon and you have an idea what’s the problem. Thank u so much...

(I also checked, that the stati of the actors are not displayed correct - light is turned on but shown as turned off/blinds are shown as down but are all the way up)

**Comment by Phasaeron** [comment]
Just a completion of my issue see the images. The physical thermostat is turned off but HomeKit shows it as turned on as it seems
![IMG_0004](https://user-images.githubusercontent.com/69851835/90513936-c1a2bf80-e160-11ea-912e-3ad2b814670b.jpeg)
![IMG_0005](https://user-images.githubusercontent.com/69851835/90513951-c9626400-e160-11ea-925c-07f3f6022b6f.jpeg)

**Comment by henry-spanka** [comment]
Hi,

I haven't really changed anything related to shutters or thermostats. Do you see some error messages in the log?

Please try to login with the same user used for hoobs in the SysAp Interface and switch a light. Then logout and restart hoobs. If that doesn't work please enable debug mode and send me the log.

**Comment by henry-spanka** [comment]
Nevermind. I found the issue. I released v2.0.3 which should fix the issue. Note that it may take a few hours for the update to be available in hoobs.

**Comment by Phasaeron** [comment]
> Nevermind. I found the issue. I released v2.0.3 which should fix the issue. Note that it may take a few hours for the update to be available in hoobs.

Sounds good. I will let you know how it worked out...

**Comment by henry-spanka** [comment]
Closing as this issue was resolved.
