### ISSUE TITLE
Missing the Trigger Acturators

### ISSUE THREAD

**Issue by oliverlinsenmaier** [henry-spanka/homebridge-freeathome#28]
I have added a Trigger Acturator to my Free@home System. It's for triggering the Garage door opener/closer. I can't find it in HomeKit or Hoobs. Is there any chance you can add it?

**Comment by henry-spanka** [comment]
Please send me a backup ("Projektsicherung") of your System Access Point via email so I can take a look.

**Comment by Alox-K** [comment]
Did he answer? Otherwise, I can provide the "Projektsicherung" as well, since I also have some Trigger acutators.

**Comment by henry-spanka** [comment]
Hi,
no he did not. Please send me the backup file via email. Thanks

**Comment by Alox-K** [comment]
Hi Henry,

this is my backup of the sysAp.

You can use this to implement the triggers. I appreciate your work for this Plugin!


Von: Henry Spanka
Gesendet: Sonntag, 11. Oktober 2020 15:08
An: henry-spanka/homebridge-freeathome
Cc: Alox-K; Comment
Betreff: Re: [henry-spanka/homebridge-freeathome] Missing the TriggerActurators (#28)

Hi,
no he did not. Please send me the backup file via email. Thanks

**Comment by henry-spanka** [comment]
Where did you send it? I can not find it in my emails.

**Comment by Alox-K** [comment]
Did you recieve my mail to yout mailadress from your profile?

**Comment by henry-spanka** [comment]
Yes, sorry for the delayed response. I will take a look at it.

**Comment by DaveMyska** [comment]
Hi Henry,
can you post the solutions here? I have exactly the same problem with trigger actuators.
Many thanks
David

**Comment by DaveMyska** [comment]
Hi Henry,
have you had a space to take a look at it? It is the last thing I am missing to be it just perfect.
Thank you
David

**Comment by captainkoehler** [comment]
Same here. Would be very happy to have my garage door integrated. Thanks in advance!

**Comment by henry-spanka** [comment]
Please open a new feature request for this if it is still relevant.
