### ISSUE TITLE
Plugin fails starting after upgrading SysAP to 2.6.0

### ISSUE THREAD

**Issue by LodieMA** [henry-spanka/homebridge-freeathome#37]
Hi, I am new here but I have an issue since I have been upgrading my SysAP from 2.5 to 2.6. Following is my log:

8/11/2020, 23:47:39 HOOBS listening on port 80.
08/11/2020, 23:47:42 Loaded plugin 'homebridge-freeathome'
08/11/2020, 23:47:42 homebridge API version: 2.6
08/11/2020, 23:47:42 [11/8/2020, 3:47:42 PM] Registering platform 'homebridge-freeathome.free@home'
08/11/2020, 23:47:42 [11/8/2020, 3:47:42 PM] Registering platform 'homebridge-freeathome.BuschJaegerSysAp'
08/11/2020, 23:47:42 Loading 1 platforms...
08/11/2020, 23:47:42 [free@home] Initializing free@home platform...
08/11/2020, 23:47:42 [free@home] Initialising BuschJaeger Plugin
08/11/2020, 23:47:42 [free@home] Will try to connect to the SysAP at 192.168.178.56
08/11/2020, 23:47:42 [free@home] Trying to connect to SysAP
08/11/2020, 23:47:44 [free@home] Sent Authenticator
08/11/2020, 23:47:44 [free@home] Received Local Key
08/11/2020, 23:47:44 [free@home] Sent New Session Request
08/11/2020, 23:47:44 [free@home] Sent Login SASL Message
08/11/2020, 23:47:44 [free@home] Received SASL Challenge
08/11/2020, 23:47:45 [free@home] Sent SASL Challenge Response
08/11/2020, 23:47:45 [free@home] Received SASL Login Confirmation
08/11/2020, 23:47:45 [free@home] Successfully Authenticated
08/11/2020, 23:47:45 [free@home] Announced Capabilities to System Access Point
08/11/2020, 23:47:45 [free@home] Requested Master Data Structure from System Access Point
08/11/2020, 23:47:46 [free@home] Received Master Update from System Acccess Point
08/11/2020, 23:47:46 (node:728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
08/11/2020, 23:47:46 at Function.parseDeviceData (/home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/XmlParser.js:110:106)
08/11/2020, 23:47:46 at Function.parseMasterUpdate (/home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/XmlParser.js:17:21)
08/11/2020, 23:47:46 at SystemAccessPoint.<anonymous> (/home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:314:53)
08/11/2020, 23:47:46 at Generator.next (<anonymous>)
08/11/2020, 23:47:46 at /home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:8:71
08/11/2020, 23:47:46 at new Promise (<anonymous>)
08/11/2020, 23:47:46 at __awaiter (/home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:4:12)
08/11/2020, 23:47:46 at SystemAccessPoint.handleRpcCallResult (/home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:293:16)
08/11/2020, 23:47:46 at SystemAccessPoint.<anonymous> (/home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:267:26)
08/11/2020, 23:47:46 at Generator.next (<anonymous>)
08/11/2020, 23:47:46 at /home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:8:71
08/11/2020, 23:47:46 at new Promise (<anonymous>)
08/11/2020, 23:47:46 at __awaiter (/home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:4:12)
08/11/2020, 23:47:46 at SystemAccessPoint.handleCryptedContainerToClient (/home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:261:16)
08/11/2020, 23:47:46 at SystemAccessPoint.<anonymous> (/home/hoobs/.hoobs/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:227:32)
08/11/2020, 23:47:46 at Generator.next (<anonymous>)
08/11/2020, 23:47:46 (node:728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
08/11/2020, 23:47:46 (node:728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by henry-spanka** [comment]
Make sure that each actuator is attached to a room/floor in the SysAp and has a name. If that doesn't solve your problem, please send me an export/backup of the SysAp to my email address.

**Comment by LodieMA** [comment]
Yep, I forgot to assign one unused actor to a room. Now it is running. Thank you!
