### ISSUE TITLE
Blacklist Hue devices

### ISSUE THREAD

**Issue by captainkoehler** [henry-spanka/homebridge-freeathome#38]
Hi! First off: I am new to homebridge, the freeathome plugin and github. So, please forgive me if this is 100% obvious to everyone else. Secondly: I totally dig what Henry has done and how it massively expands what you can do with your Busch-Jaeger system as a result. Now on to my question: Can I blacklist my (HomeKit compatible) Philips Hue devices and prevent them from showing up twice in the Home app? And if so, how? I am not sure which ID to use and where to find that.

**Comment by Alox-K** [comment]
Hi!
Usually, it should work like this:
"Plugins" - Freeathome-Plugin: "Configure" - "Custom Mappings"

`{
    "<#BEEDF9BE000E>": {
        "blacklist": [
            "ch0000"
        ]
    }
}`

You can find the ID in "Protocol", where you need to look for the device, you want to blacklist and copy it from there.

But actually, it didn't work on this way in my system. I think the general way should be right, but there seems to be some issue.

**Comment by henry-spanka** [comment]
@Alox-K is correct. You can actually find the serial no and ID in the settings of the accessory in the HomeKit app.

**Comment by Alox-K** [comment]
Hey Henry!

I'm sorry - but the blacklisting seems to have a problem. Or maybe I did it wrong.

![IMG_0203](https://user-images.githubusercontent.com/66076758/100479031-549eae80-30ed-11eb-8943-974bc478ddc3.JPG)

This is the device, i'd like to blacklist.
I took the serialnumber and model and pasted it to the config-window:

![2020-11-27 20_17_43-Window](https://user-images.githubusercontent.com/66076758/100479188-bced9000-30ed-11eb-95ef-323956b988b5.png)

This one and even the native buschjäger-device are still visible in homekit.

I tried to add "#" in front of the serial and tried the "modell" with and without the second number.  Reboot didn't help either. No effect at all. 

Any idea?

**Comment by henry-spanka** [comment]
Your mapping is incorrect. Please try this:

```json
{
  "BEEDF9BE000E": {
    "blacklist": [
      "ch0000"
    ]
  },
  "ABB700CD51F9": {
    "blacklist": [
      "ch0009"
    ]
  }
}
```

**Comment by Alox-K** [comment]
Awesome! This works! Thank you for your help!
The Paragraph       ```
  "<ACTUATOR-SERIAL>": {
            "blacklist": ["ch0000", "ch0001"],
        },
```
...of your Description Page lebt me think, i need the <>.

**Comment by captainkoehler** [comment]
Thank you, gents! That has fixed it for me as well.
