### ISSUE TITLE
uninstantiable device

### ISSUE THREAD

**Issue by hs75** [henry-spanka/homebridge-freeathome#39]
dear all,

installation works partially with me - some devices however are not recognised as follows. any suggestions?

best, h

xxx and yyy are numbers and text replaced for confidentiality

Nov 16 07:51:37 raspberrypi homebridge[17495]: BEEDxxxxxxxxx 10C0
Nov 16 07:51:37 raspberrypi homebridge[17495]: uninstantiable device {
Nov 16 07:51:37 raspberrypi homebridge[17495]:   serialNumber: 'BEEDxxxxxxxx',
Nov 16 07:51:37 raspberrypi homebridge[17495]:   deviceId: '10C0',
Nov 16 07:51:37 raspberrypi homebridge[17495]:   typeName: 'Hue Aktor',
Nov 16 07:51:37 raspberrypi homebridge[17495]:   channels: {
Nov 16 07:51:37 raspberrypi homebridge[17495]:     ch0000: {
Nov 16 07:51:37 raspberrypi homebridge[17495]:       datapoints: [Object],
Nov 16 07:51:37 raspberrypi homebridge[17495]:       displayName: 'yyyyyyyyy',
Nov 16 07:51:37 raspberrypi homebridge[17495]:       floor: 'Dachgeschoss',
Nov 16 07:51:37 raspberrypi homebridge[17495]:       room: 'Bad',
Nov 16 07:51:37 raspberrypi homebridge[17495]:       iconId: '6a',
Nov 16 07:51:37 raspberrypi homebridge[17495]:       functionId: '2e'
Nov 16 07:51:37 raspberrypi homebridge[17495]:     }
Nov 16 07:51:37 raspberrypi homebridge[17495]:   }
Nov 16 07:51:37 raspberrypi homebridge[17495]: }

**Comment by henry-spanka** [comment]
Not all hue actuators are supported at the moment. Please send me a backup of your project to my email address.

**Comment by henry-spanka** [comment]
Closing due to no response.
