### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Jimpansen0815** [henry-spanka/homebridge-freeathome#47]
Hello, everyone, I wanted to configure the plugin today, but unfortunately I always get an error message after rebooting. Can anyone help me?

![FFAD8F76-9909-4C7B-A4DC-465B955B1631](https://user-images.githubusercontent.com/78278291/106500098-b569af00-64c1-11eb-8929-29790718d1a3.jpeg)

**Comment by Tsuktis** [comment]
Please see:
https://github.com/henry-spanka/homebridge-freeathome/issues/37

**Comment by Jimpansen0815** [comment]
perfect, everything worked out.

Only the panel does not recognize the bridge as a room thermostat
