### ISSUE TITLE
wireless thermostat and windows contacts

### ISSUE THREAD

**Issue by marko-75** [henry-spanka/homebridge-freeathome#49]
Herny,
hope you are well.
First of all, thanks for this Busch-Jäger plug-in.
Most of my devices are shown properly as devices (in homebridge) and can be managed via home app (lights, roller shutter).
What I can't see (and manage) are my wireless thermostats and the window contacts. The generic contacts (Universalmelder) are shown, but not the door/window ones.

Any help appreciate.
Thanks
Marko

**Comment by floriangrotz** [comment]
See #33 and #35

**Comment by marko-75** [comment]
@floriangrotz - thanks for the link to the other issues. But basically those links end in the statement "please send your backup to check therein" or did I missed something. I have send my backup to Henry as well.
Please advise how to solve this issue. Thanks!

**Comment by henry-spanka** [comment]
Closing because there is another issue for this.
