### ISSUE TITLE
Add Slat Support for Blinds (Jalousien)

### ISSUE THREAD

**Issue by floriangrotz** [henry-spanka/homebridge-freeathome#50]
Please add Slat Support for Blinds (Jalousien)

[Jalousie Actuator](https://www.busch-jaeger.de/produktuebersicht?tx_nlbjproducts_catalog%5Baction%5D=show&tx_nlbjproducts_catalog%5BcatBjeProdukt%5D=3813&tx_nlbjproducts_catalog%5Bcontroller%5D=CatStdArtikel&cHash=f5baa206f7d09939a5aa2485ac44a562) 

![345405C9-7F15-4F51-8E68-EECBB0BEF2C7](https://user-images.githubusercontent.com/63972904/110464181-201a9580-80d3-11eb-9590-eff17514cd85.jpeg)

![E2282CDD-B1CD-4550-A8DC-B8DB074EEA74](https://user-images.githubusercontent.com/63972904/110464992-26f5d800-80d4-11eb-82c4-c2a7ab375c05.jpeg)

Documentation on HomeKit

https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types

> Tilting Mechanisms

**Comment by claudemangen** [comment]
Hello,

me too, I would also appreciate it a lot, if you could add slat support for blinds.

Thanks

**Comment by henry-spanka** [comment]
Please let me know if you are still interested in it. I need someone to test it because I don't have slat blinds.

**Comment by floriangrotz** [comment]
Yes. Please also take a look at #46

**Comment by henry-spanka** [comment]
Okay. The blinds are working. You are just missing slat support right? Please enable homebridge debug mode and control the slats manually and send me the logs.

**Comment by claudemangen** [comment]
Hello,

yes, still very interested in this feature. I send you the logs to your mail address.

Thanks in advanced.

**Comment by henry-spanka** [comment]
Thanks. I'll add slat support in the next release when we switch to the local API.

**Comment by MaxV85** [comment]
> Thanks. I'll add slat support in the next release when we switch to the local API.

Dear Henry, 

i managend to get working your plugin. But I don't know how to get the slat support working. I installed the most recent version and did nothing special or change the config anyhow. Can you imagine what I am doing wrong?

**Comment by henry-spanka** [comment]
Hi Max,

currently there is no slat support yet. Please send me an email (listed in my GitHub profile) and I'll send you next steps. I need to get some data from your system to be able to add this functionality as my blinds do not have slat support.

**Comment by DaveMyska** [comment]
Hey, Henry,
did you get all the information you need to implement the slats control?
I can send you whatever you need.
Thank you

**Comment by henry-spanka** [comment]
Hi Dave,
please send me a backup of your free@home Configuration (Project Export in SysAp Web UI) and the model number of the blinds you have via email.

Thanks

**Comment by henry-spanka** [comment]
Happy to share that we now finally have horizontal slats support. Update the plugin to version 2.0.7 or later.
