### ISSUE TITLE
6241/4.0 Binary Sensor doesn't update in HK

### ISSUE THREAD

**Issue by Mischmasch44** [henry-spanka/homebridge-freeathome#53]
Hello,

I use the 6241/4.0 free@home binary sensor with attached reed window contacts. These work fine in free@home, but don't seem to update in HomeKit. If I open/close a window, the Homebridge log states that the accessory was updated, but the status of the window doesn't change. I looked in the device section of Homebridge and in HomeKit. I don't know if only the impuls is send or the window contact is always updated to closed, no matter if the window is opened or closed. Maybe I do something wrong. 
The rest of the plugin works amazing and I'm glad that I have the possibility to use it. It helps a lot!
Is it the same problem as in #12?
Please help :(

**Comment by henry-spanka** [comment]
Closing as there is another issue for this
