### ISSUE TITLE
all shutters and blinds have category "Klima" in Home-App

### ISSUE THREAD

**Issue by Daniel-Duesentrieb** [henry-spanka/homebridge-freeathome#67]
Hi, 
is it normal, that all shutters and blinds have the category "Klima" like fans and stuff like that in the Apple Home-App?
I was expecting a more appropriate category. 
Kind regards. 
![IMG_0365](https://user-images.githubusercontent.com/123842530/215295035-26d586dc-b9e2-477c-a088-05f66a263392.jpeg)

**Comment by floriangrotz** [comment]
It’s no big - it’s a feature.
Homekit is summarizing in Climate
- Heating
- Cooling 
- — air condition
- — fan
- Temperature
- Humidity 
- CO2

**Comment by henry-spanka** [comment]
As @floriangrotz already said, the categories are fixed by Apple and cannot be changed. Any shutters and blinds are automatically categorised under Climate and it makes sense because shutters are used to control the climate within your house.
