### ISSUE TITLE
ECONNREFUSED - Connection error

### ISSUE THREAD

**Issue by yannmaniez71** [henry-spanka/homebridge-freeathome#68]
I receive this message when I try to connect with homebridge to my SysAp.

I tried lot of configurations, but no results.

Can you help me ?

Error received Error: connect ECONNREFUSED 192.168.1.180:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.180',
  port: 443
}

Sorry for my English, I am not so fluent.

**Comment by henry-spanka** [comment]
Hi,
make sure that you can reach your SysAp at IP 192.168.1.180. Can you log into the Web Interface of the SysAp via this IP Address?

**Comment by yannmaniez71** [comment]
Hi,

Yes I do.

**Comment by yannmaniez71** [comment]
Hi, 

I remake my Install completely, I remote my VPN server on my raspberry and it works.
I finished the configuration like you said and it works. 
Sorry for casting your time.
Thanks for your help.

Yann

**Comment by henry-spanka** [comment]
👍
